name: Build MOS Frontend

on:
  # Trigger build manually
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Remove dist directory
      run: rm -rf ${{ github.workspace }}/dist

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.13.0'

    - name: Get latest noVNC and add it to public
      id: novnc
      run: |
        wget https://github.com/novnc/noVNC/archive/refs/heads/master.tar.gz -O novnc.tar.gz
        mkdir -p public/novnc
        tar -C public/novnc/ --strip-components=1 -xf novnc.tar.gz
        rm -rf public/novnc/{.github,.gitignore,.gitmodules,docs,eslint.config.mjs,karma.conf.cjs,po,README.md,snap,tests,utils}
        awk '/EMBEDDING.md/ {
            print;
            print ""
            print "        // MOS Custom: Set VM icon as favicon and title from URL params";
            print "        const urlParams = new URLSearchParams(window.location.search);";
            print "        const iconParam = urlParams.get('\''icon'\'');";
            print "        const titleParam = urlParams.get('\''title'\'');";
            print "        if (iconParam) {";
            print "            const link = document.querySelector(\"link[rel='\''icon'\'']\") || document.createElement('\''link'\'');";
            print "            link.type = '\''image/png'\'';";
            print "            link.rel = '\''icon'\'';";
            print "            link.href = iconParam;";
            print "            document.head.appendChild(link);";
            print "        }";
            print "        if (titleParam) {";
            print "            document.title = `VNC - ${titleParam}`;";
            print "        }";
            next;
        }
        {print}' public/novnc/vnc.html > temp && mv temp public/novnc/vnc.html

    - name: Install dependencies
      run: npm install

    - name: Build MOS Frontend
      run: npm run build

    - name: Fetch tags
      run: git fetch --tags

    - name: Get next version
      id: version
      run: |
        LAST_TAG=$(curl -s --request GET \
            --url "https://api.github.com/repos/ich777/mos-frontend/releases?per_page=50" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "X-GitHub-Api-Version: 2022-11-28" | jq -r '.[].tag_name' | sort -V | tail -1)
        echo "Last tag: $LAST_TAG"

        if [[ $LAST_TAG =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
          MAJOR=${BASH_REMATCH[1]}
          MINOR=${BASH_REMATCH[2]}
          PATCH=${BASH_REMATCH[3]}
          NEXT_PATCH=$((PATCH + 1))
          NEXT_TAG="${MAJOR}.${MINOR}.${NEXT_PATCH}"
        fi

        echo "Next tag: $NEXT_TAG"
        echo "NEXT_TAG=${NEXT_TAG#v}" >> $GITHUB_ENV

    - name: Create Release Archive
      run: |
        cd ${{ github.workspace }}
        tar -czf mos-frontend-${{ env.NEXT_TAG }}.tar.gz -C dist .
        md5sum mos-frontend-${{ env.NEXT_TAG }}.tar.gz | awk '{print $1}' > mos-frontend-${{ env.NEXT_TAG }}.tar.gz.md5

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEXT_TAG }}
        release_name: "MOS Frontend ${{ env.NEXT_TAG }}"
        body: "MOS-Frontend - Built from commit: ${{ github.sha }}"
        draft: false
        prerelease: ${{ env.PRERELEASE }}

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/mos-frontend-${{ env.NEXT_TAG }}.tar.gz
        asset_name: mos-frontend-${{ env.NEXT_TAG }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload md5 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/mos-frontend-${{ env.NEXT_TAG }}.tar.gz.md5
        asset_name: mos-frontend-${{ env.NEXT_TAG }}.tar.gz.md5
        asset_content_type: text/plain
